name: Youtube workflow
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest videos from Youtube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eralmendral/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxzLpRFB3ogK7SrbyQ_NelA"
